version: 2.1

commands:
  install-deps:
    steps:
    - run:
        name: Install dep
        command: |
          cd src
          npm ci

jobs:
  unit-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install-deps
      - run:
          name: unit-test
          command: |
            cd src
            npm run test-unit
  

workflows:
  build-and-packge:
    jobs:
      - unit-test
      