version: 2.1

commands:
  install-deps:
    steps:
    - run:
        name: Install dep
        command: |
          cd src
          npm ci

jobs:
  unit-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install-deps
      - run:
          name: unit-test
          command: |
            cd src
            npm run test-unit

  test-lint:
    docker:
        - image: circleci/node:lts
    steps:
      - checkout
      - install-deps
      - run:
          name: test-lint
          command: |
            cd src
            npm run test-lint
  
  code-coverage:
    docker:
        - image: circleci/node:lts
    steps:
      - checkout
      - install-deps
      - run:
          name: code-coverage
          command: |
            cd src
            npm run test-coverage

  failure-condition:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install-deps
      - run:
          name: Install NodeJsScan
          command: |
            cd src
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run:
          name: Run NodeJsScan
          command: |
            cd src
            nodejsscan -d ./src -o sast-output.json
      - store_artifacts:
          path: sast-output.json
      - run:
          name: Parse sast report
          command: |
            exit $(cat ./src/sast-output.json | jq .total_count.sec)   
  
  package:
    docker:
        - image: circleci/node:lts
    steps:
      - checkout
      - install-deps
      - run:
          name: Package
          command: |
            cd src
            npm pack
      - store_artifacts:
          path: ./src/simpletodoapp-1.0.0.tgz
          destination: simpletodoapp-1.0.0.tgz

  integration-test:
    docker:
        - image: circleci/node:lts
        - image: mongo:4.0
    steps:
      - checkout
      - install-deps
      - run:
          name: integration test
          command: |
            cd src
            npm run test-integration

  e2e-test:
    docker:
        - image: circleci/node:lts
    steps:
      - checkout
      - install-deps
      - setup_remote_docker 
      - run:
          name: e2e-test
          command: |
            chmod +x scripts/e2e-ci.sh
            ./scripts/e2e-ci.sh



  
workflows:
  build-and-packge:
    jobs:
      - unit-test
      - test-lint
      - code-coverage
      - failure-condition
      - package:
          filters:
            branches:
              only:
                - master
      - integration-test
      - e2e-test
          
  
                   
                  
                

      