version: 2.1

commands:
  install-deps:
    steps:
    - run:
        name: Install dep
        command: |
          cd src
          npm ci
          
jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout

workflows:
  build-and-packge:
    jobs:
      - ci-build
